name: duo_hao
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# ==============Start支持iOS Android web win linux macOS 的库Start=========================
  cupertino_icons: ^1.0.2
  dio: ^4.0.0 # 网络库
  flutter_screenutil: ^5.0.0 #屏幕适配
  pull_to_refresh: ^1.6.5  #刷新组件
  url_launcher: ^6.0.3 # 拉起url
  event_bus: ^2.0.0 #事件总线
  get: ^4.1.4 #状态管理
  get_storage: ^2.0.2 #内存 键值 存取
  shared_preferences: ^2.0.5 #磁盘 键值 存取
  flutter_swiper: ^1.1.6 # 轮播
  bot_toast: ^4.0.1 #一个真正意义上的flutter Toast库
  badges: ^1.2.0 #小红点
  qr_flutter: ^4.0.0 #二维码
  photo_view: ^0.11.1 #图片预览
  path_provider: ^2.0.1 #获取APP路径
  device_info_plus: ^1.0.0  #设备信息
  octo_image: ^1.0.0+1 # 支持占位图 错误图 加载进度
  convex_bottom_bar: ^3.0.0 # 底部tab
  pedantic: ^1.11.0 #编码规范

  #工具
  dio_log : ^2.0.0 #app内抓包工具
  logger: ^1.0.0 #日志库
  device_preview: ^0.7.1 #不同分辨率查看效果
# ==============end 支持iOS Android web win linux macOS 的库 end =========================

# ===========Start 仅支持iOS Android  的库 Start=========================
  image_gallery_saver: ^1.6.9 #保存图片至本地
  permission_handler: ^6.1.3 #权限管理
  flutter_inappwebview: ^5.3.2 # APP 内嵌web
  multi_image_picker: ^4.8.0 #图片选择器

  # image_picker: ^0.7.4 #图片选择器备用 wechat_assets_picker: ^5.1.2
  #jpush_flutter: ^2.0.1 #极光推送备用

  #工具包
#  dokit: ^0.2.14  #暂不支持flutter2.0 滴滴工具: 提供了日志、method channel信息、路由信息、网络抓包、帧率、设备与内存信息查看、控件信息查看功能.
# ===========end 仅支持iOS Android  的库 end =========================
dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - static/images/3.0x/
    - static/images/
    - static/
