name: flutter_APP
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.4.0 # 网络库
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.1.14
  event_bus: ^2.0.0 #事件总线
  get: ^4.6.5 #状态管理
  get_storage: ^2.0.3 #内存 键值 存取

  bot_toast: ^4.0.2 #Toast库
  badges: ^2.0.3 #小红点

#  device_info_plus: ^9.1.1

  date_format: ^2.0.6
  flutter_picker: ^2.0.3 #选择器
  custom_pop_up_menu: ^1.2.4

  talker_dio_logger: ^2.3.3
  logger: ^2.0.2+1 #日志库
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.3

  image_gallery_saver: ^2.0.3
  buttons_tabbar: ^1.3.8
  flutter_animated_dialog: ^2.0.1

  easy_refresh: ^3.3.4
  card_swiper: ^3.0.1
  package_info_plus: ^3.1.2 # 包信息


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - static/images/
    - static/
